### ISSUE TITLE
Integrate CKeditor

### ISSUE THREAD

**Issue by andrewboon** [unaio/una#223]
Integrate http://ckeditor.com/ as a main text editor instead of TinyMCE. Main reasons are support of copy-paste image uploads and better mobile support. Also development of the editor is more dynamic than TinyMCE.

Upload of images via clipboard paste should also add them to the Trident's attached images list (trident file-manager), for cases when it needs to be used as post  thumbnail, or re-used via future file-manager.

**Comment by andreyasko** [comment]
https://github.com/unaio/una/issues/479
