### ISSUE TITLE
Charts!!!

### ISSUE THREAD

**Issue by AlexTr** [unaio/una#363]
Use the same system as in Dolphin but with [ChartJS](https://github.com/chartjs/Chart.js) library.  The same two blocks as in Dolphin admin:
- grows charts, based on this - http://www.chartjs.org/samples/latest/charts/line/basic.html
- all content, based on this - http://www.chartjs.org/samples/latest/charts/doughnut.html

By default add Chart blocks on user's Dashboard page, make block copyable, so it can be copied somewhere else.
Access to charts should be controlled via Permissions, default access is for Administrators only.

If possible make grouping by day, week, month.

**Comment by newton27** [comment]
Still badly needed.
